# Generated by Django 5.0.7 on 2024-08-03 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان(به فارسی)')),
                ('url_name', models.CharField(max_length=300, verbose_name='عنوان در url(به انگلیسی)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال/غیرفعال')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='حذف شده/حذف نشده')),
                ('title_english', models.CharField(max_length=200, verbose_name='نام برند(به انگلیسی)')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان(به فارسی)')),
                ('url_name', models.CharField(max_length=300, verbose_name='عنوان در url(به انگلیسی)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال/غیرفعال')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='حذف شده/حذف نشده')),
                ('title_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.category', verbose_name='دسته بنده')),
            ],
            options={
                'verbose_name': 'دسته بنده ها',
                'verbose_name_plural': 'دسته بندی',
            },
        ),
    ]
