# Generated by Django 5.0.7 on 2024-08-03 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_brands_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category_product',
            field=models.ManyToManyField(db_index=True, null=True, to='products.category', verbose_name='دسته بندی'),
        ),
    ]
