# Generated by Django 5.0.7 on 2024-09-05 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_productvisit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='درصد تخفیف'),
        ),
    ]
