# Generated by Django 5.0.7 on 2024-09-05 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_product_sale_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_percent',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='درصد تخفیف'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_price',
            field=models.IntegerField(default=0, verbose_name='تخفیف'),
        ),
    ]
