# Generated by Django 5.0.7 on 2024-09-05 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_product_discount_percent_alter_product_sale_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sale_price',
            field=models.IntegerField(default=0, verbose_name='قیمت تخفیف'),
        ),
    ]
