# Generated by Django 5.0.7 on 2024-09-11 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_product_sale_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category_product',
            field=models.ManyToManyField(db_index=True, to='products.category', verbose_name='دسته بندی'),
        ),
    ]
