# Generated by Django 5.0.7 on 2024-09-11 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_product_category_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_galry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/images/galry')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال/غیرفعال')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='حذف شده/حذف نشده')),
                ('product_gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='گالری')),
            ],
        ),
    ]
