# Generated by Django 5.0.7 on 2024-09-16 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_product_galry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment_product',
        ),
    ]
