# Generated by Django 5.0.7 on 2024-09-16 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'کامنت', 'verbose_name_plural': 'کامنت ها'},
        ),
    ]
