# Generated by Django 5.0.7 on 2024-09-21 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_comment_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='پاک کردن _ نکردن'),
        ),
    ]
